#!/usr/bin/env bash
# update-wasm-checksums.sh
#
# Rebuilds the WASM artifact and updates wasm/checksums.sha256 with the
# fresh SHA256. Run this locally whenever contract source changes and
# commit the updated checksums file alongside your code change.
#
# Usage: bash script/update-wasm-checksums.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM_FILE="${REPO_ROOT}/target/wasm32-unknown-unknown/release/fluxora_stream.wasm"
CHECKSUMS_FILE="${REPO_ROOT}/wasm/checksums.sha256"

echo "Building WASM (release)..."
cargo build --release -p fluxora_stream --target wasm32-unknown-unknown \
  --manifest-path "${REPO_ROOT}/Cargo.toml"

if [ ! -f "${WASM_FILE}" ]; then
  echo "ERROR: WASM artifact not found at ${WASM_FILE}" >&2
  exit 1
fi

NEW_HASH=$(sha256sum "${WASM_FILE}" | awk '{print $1}')
echo "New SHA256: ${NEW_HASH}"

# Rewrite the checksums file, preserving the header comments
HEADER=$(grep '^#' "${CHECKSUMS_FILE}")
TODAY=$(date +%Y-%m-%d)

cat > "${CHECKSUMS_FILE}" <<EOF
# Fluxora Stream WASM Checksums
#
# This file contains reference SHA256 checksums for reproducible WASM builds.
# CI verifies that a fresh build produces byte-identical artifacts.
#
# Format: <sha256>  <filename>
# Generated by: script/update-wasm-checksums.sh
# Last updated: ${TODAY}
#
# To regenerate, run: bash script/update-wasm-checksums.sh
#
# Determinism contract:
#   - Rust toolchain is pinned via rust-toolchain.toml (stable channel)
#   - soroban-sdk version is pinned in contracts/stream/Cargo.toml
#   - Build uses --release with wasm32-unknown-unknown target
#   - No environment-dependent flags or features beyond the pinned toolchain
#
${NEW_HASH}  fluxora_stream.wasm
EOF

echo "Updated ${CHECKSUMS_FILE}"
echo "Commit this file alongside your source changes."
